<?php
function dummy_paragraph(){
    return array(
        'lorem' => array(
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
            'Hinc ceteri particulas arripere conati suam quisque videro voluit afferre sententiam.',
            'Quorum sine causa fieri nihil putandum est.',
            'In his igitur partibus duabus nihil erat, quod Zeno commutare gestiret.',
            'At, si voluptas esset bonum, desideraret.',
            'Sed haec quidem liberius ab eo dicuntur et saepius.',
            'Comprehensum, quod cognitum non habet?',
            'Hanc ergo intuens debet institutum illud quasi signum absolvere.',
            'Sin dicit obscurari quaedam nec apparere, quia valde parva sint, nos quoque concedimus;',
            'Cur, nisi quod turpis oratio est?',
            'Quod maxime efficit Theophrasti de beata vita liber, in quo multum admodum fortunae datur.',
            'Huius ego nunc auctoritatem sequens idem faciam.',
            'Duo Reges: constructio interrete.',
            'Eadem nunc mea adversum te oratio est.',
            'Scio enim esse quosdam, qui quavis lingua philosophari possint;',
            'Non quam nostram quidem, inquit Pomponius iocans; ',
            'orem ipsum dolor sit amet, consectetur adipiscing elit.',
            'Si quae forte-possumus.',
            'Expressa vero in iis aetatibus, quae iam confirmatae sunt.',
            'Hos contra singulos dici est melius.',
            'Quodcumque in mentem incideret, et quodcumque tamquam occurreret.',
            'Eodem modo is enim tibi nemo dabit, quod, expetendum sit, id esse laudabile.',
            'Piso, familiaris noster, et alia multa et hoc loco Stoicos irridebat: Quid enim?',
            'Illa argumenta propria videamus, cur omnia sint paria peccata.',
            'Habent enim et bene longam et satis litigiosam disputationem.',
            'Collige omnia, quae soletis: Praesidium amicorum.',
            'Quae cum praeponunt, ut sit aliqua rerum selectio, naturam videntur sequi;',
            'Duo Reges: constructio interrete.',
            'Totum autem id externum est, et quod externum, id in casu est.',
            'In schola desinis. Urgent tamen et nihil remittunt.',
            'Quicquid porro animo cernimus, id omne oritur a sensibus;',
            'In schola desinis.',
            'At eum nihili facit;',
            'Ergo in utroque exercebantur, eaque disciplina effecit tantam illorum utroque in genere dicendi copiam.',
            'Quod quidem iam fit etiam in Academia.',
            'Qua ex cognitione facilior facta est investigatio rerum occultissimarum.',
            'Duo Reges: constructio interrete.',
            'Portenta haec esse dicit, neque ea ratione ullo modo posse vivi;',
            'Quamquam ab iis philosophiam et omnes ingenuas disciplinas habemus;',
            'Cum audissem Antiochum, Brute, ut solebam, cum M.',
            'Est enim effectrix multarum et magnarum voluptatum.',
            'Si longus, levis.',
            'Hinc ceteri particulas arripere conati suam quisque videro voluit afferre sententiam.',
            'Quodcumque in mentem incideret, et quodcumque tamquam occurreret.',
            'Quod autem principium officii quaerunt, melius quam Pyrrho;',
            'Re mihi non aeque satisfacit, et quidem locis pluribus.',
            'Suo enim quisque studio maxime ducitur.',
            'Inde sermone vario sex illa a Dipylo stadia confecimus.',
            'Aliud igitur esse censet gaudere, aliud non dolere.',
            'Quae contraria sunt his, malane?',
            'Torquatus, is qui consul cum Cn.',
            'Qui est in parvis malis.',
            'Facit enim ille duo seiuncta ultima bonorum, quae ut essent vera, coniungi debuerunt;',
            'Illa sunt similia: hebes acies est cuipiam oculorum, corpore alius senescit;',
            'Ita enim vivunt quidam, ut eorum vita refellatur oratio.',
        )
    );
}
